[package]
name = "assign1_piaic84325"
version = "0.1.0"
edition = "2018"
authors = ["alirazaliqadri_piaic"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio =  {version="0.2.*",features=["full"]}